<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>6c775d27-a1c5-4012-818f-b2cbaa886efd</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Hangfire" Version="1.8.23" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
		<PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
		<PackageReference Include="MailKit" Version="4.16.0" />
		<PackageReference Include="MimeKit" Version="4.16.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WazzufJobs.BLL\WazzufJobs.BLL.csproj" />
		<ProjectReference Include="..\WazzufJobs.DAL\WazzufJobs.DAL.csproj" />
		<ProjectReference Include="..\WazzufJobs.Shared\WazzufJobs.Shared.csproj" />
	</ItemGroup>
</Project>